# Generated by Django 4.1.5 on 2023-01-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
