# Generated by Django 4.1.5 on 2023-01-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_comment_is_active_comment_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='recommend',
        ),
    ]
